// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://reobzqoswxzuouqyfmyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlb2J6cW9zd3h6dW91cXlmbXloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5Mzg0MjEsImV4cCI6MjA2NzUxNDQyMX0.Ff0cEza2T3Iun-GNwOMgif_Y5FYVa3HS-gg20WL8HKM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});